language: generic
sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t hakimix/docker-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true hakimix/docker-workflow npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-workflow"
  env: "Dockerworkflow-env"
  bucket_name: "elasticbeanstalk-eu-west-1-933021064415"
  bucket_path: "docker-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
