version: '3'
services:
  frontend:
    build:
      context: frontend # the location of the project files
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
